---
variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386
  - &repo bksolutions/picapport


steps:
  prepare:
    image: woodpeckerci/plugin-git
    commands:
      - echo "Must be tagged"
    when:
      - evaluate: 'GIT_DIR=./.git git tag --list | grep -q "^10.0.04$"'

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: false
      repo: *repo
      tags: 
        - 'latest'
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS
    when:
      branch: build