---
variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/amd64,linux/i386,linux/arm/v7,linux/arm64/v8
  - &repo bksolutions/picapport


steps:
  prepare-global:
    group: pull
    image: alpine/curl
    commands:
      - echo 'Get list of available Versions:'
      - curl https://www.picapport.de/de/photo-server-download.php --silent | sed -En "s/.*dlfile=(.*)%2fpicapport-headless.jar\"/\1/p" > picapport.vers
      - cat ./picapport.vers

      - echo 'Get latest version:'
      - sed -n '1p' picapport.vers > latest.vers
      - cat ./latest.vers

      - echo 'Create download link (latest):'
      - sed -En "s/([0-9\-]*).*/https:\\/\\/www.picapport.de\\/download\\/\1\\/picapport-headless.jar --output picapport-headless-\1.jar/p" ./latest.vers > latest.url
      - cat ./latest.url

  prepare-10-4.00:
    group: pull
    image: alpine/curl
    commands:
      - curl https://www.picapport.de/download/10-4-00/picapport-headless.jar --output ./picapport-headless-10-4-00.jar

  prepare-10-3.01:
    group: pull
    image: alpine/curl
    commands:
      - curl https://www.picapport.de/download/10-3-01/picapport-headless.jar --output ./picapport-headless-10-3-01.jar


  10-4-00:
    image: woodpeckerci/plugin-docker-buildx
    group: build
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: false
      repo: *repo
      tags: 
        - '10.4.00'
        - 'latest'
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS
    when:
      branch: main

  10-3-01:
    image: woodpeckerci/plugin-docker-buildx
    group: build
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: false
      repo: *repo
      tags: 
        - '10.3.01'
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS
    when:
      branch: main