---

variables:
  - &img alpine/curl
  - &branch main

steps:
  prepare:
    image: *img
    commands:
      - echo 'Get list of available Versions:'
      - curl https://www.picapport.de/de/photo-server-download.php --silent | sed -En "s/.*dlfile=(.*)%2fpicapport-headless.jar\"/\1/p" > picapport.vers
      - cat ./picapport.vers

      - echo 'Get latest version:'
      - sed -n '1p' picapport.vers > latest.vers
      - cat ./latest.vers

      - echo 'Create download link (latest):'
      - sed -En "s/([0-9\-]*).*/https:\\/\\/www.picapport.de\\/download\\/\1\\/picapport-headless.jar --output picapport-headless-\1.jar/p" ./latest.vers > latest.url
      - cat ./latest.url
    when:
      branch: *branch

  update:
    image: *img
    commands: 
      - rm -f ./.woodpecker/.deploy*.yaml
      - sed "s/<VERSION>/$(sed -n '1p' ./picapport.vers | tr -d '[:space:]')/g" ./.woodpecker/.deploy.tpl > ./.woodpecker/deploy_$(sed -n '1p' ./picapport.vers | tr -d '[:space:]').yaml
      - sed -i "/tags:/a \ \ \ \ \ \ \ \ - latest" ./.woodpecker/deploy_$(sed -n '1p' ./picapport.vers | tr -d '[:space:]').yaml
      - tail -n +2 ./picapport.vers > ./picapport.tmp && mv ./picapport.tmp ./picapport.vers
      - ls -la .woodpecker/*.yaml
      - |
        while [ -s ./picapport.vers ]
        do
          sed "s/<VERSION>/$(sed -n '1p' ./picapport.vers | tr -d '[:space:]')/g" ./.woodpecker/.deploy.tpl > ./.woodpecker/deploy_$(sed -n '1p' ./picapport.vers | tr -d '[:space:]').yaml
          tail -n +2 ./picapport.vers > ./picapport.tmp && mv ./picapport.tmp ./picapport.vers
        done
      - ls -la ./.woodpecker
    when:
      branch: *branch

    verify:
      image: *img
      commands:
        - |
          for f in ./.woodpecker/*.yaml
          do
            cat $f
          done