---

variables:
  - &img alpine/curl

steps:
  - name: prepare-versions-list
    when:
      - event: [push, tag, deployment]
        branch: [main]
        path:
          include: ['Dockerfile', '*.sh']
          ignore_message: '[ALL]'
          on_empty: true
    image: *img
    commands:
      - echo 'Get list of available Versions:'
      - curl https://www.picapport.de/de/photo-server-download.php --silent | sed -En "s/.*dlfile=(.*)%2fpicapport-headless.jar\"/\1/p" > picapport.vers
      - cat ./picapport.vers

      - echo 'Get latest version:'
      - sed -n '1p' picapport.vers > latest.vers
      - cat ./latest.vers

      - echo 'Create download link (latest):'
      - sed -En "s/([0-9\-]*).*/https:\\/\\/www.picapport.de\\/download\\/\1\\/picapport-headless.jar --output picapport-headless-\1.jar/p" ./latest.vers > latest.url
      - cat ./latest.url


      - rm -f ./.woodpecker/.deploy*.yaml
      - sed "s/<VERSION>/$(sed -n '1p' ./picapport.vers | tr -d '[:space:]')/g" ./.woodpecker/.deploy.tpl > ./.woodpecker/deploy_$(sed -n '1p' ./picapport.vers | tr -d '[:space:]').yaml
      - sed -i "/tags:/a \ \ \ \ \ \ \ \ - latest" ./.woodpecker/deploy_$(sed -n '1p' ./picapport.vers | tr -d '[:space:]').yaml
      - tail -n +2 ./picapport.vers > ./picapport.tmp && mv ./picapport.tmp ./picapport.vers
      - ls -la .woodpecker/*.yaml
      - |
        while [ -s ./picapport.vers ]
        do
          sed "s/<VERSION>/$(sed -n '1p' ./picapport.vers | tr -d '[:space:]')/g" ./.woodpecker/.deploy.tpl > ./.woodpecker/deploy_$(sed -n '1p' ./picapport.vers | tr -d '[:space:]').yaml
          tail -n +2 ./picapport.vers > ./picapport.tmp && mv ./picapport.tmp ./picapport.vers
        done
      - ls -la ./.woodpecker


      - |
        for f in ./.woodpecker/*.yaml
        do
          echo "$f: "
          cat $f
          echo ""
        done


  - name: push
    depends_on: [prepare-versions-list]
    image: appleboy/drone-git-push
    settings:
      branch: release
      remote: ssh://git@github.com/kca-docker/picapport.git
      ssh_key: 
        from_secret: GITHUB_SSH_KEY
      force: true
      commit: true
      commit_message: "Create new CI/CD Release configurations..."